#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2.5
bspc config window_gap          12

bspc config normal_border_color "#3c3836"
bspc config focused_border_color "#fabd2f" 
bspc config urgent_border_color "#fb4934"  
bspc config presel_border_color "#83a598"  

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a mpv \
     state=floating sticky=on follow=off focus=on \
     rectangle=640x360+1280+720
bspc rule -a "*:Toolkit:Picture-in-Picture" \
     state=floating sticky=on follow=off focus=on \
     rectangle=640x360+1280+720

#auto start
polybar &
dunst &
picom &
fcitx5 &
feh --bg-fill --randomize ~/Downloads/wallpaper/* &  --bg-fill --randomize ~/Downloads/wallpaper/* & 
