#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width 2.5
bspc config window_gap 12

bspc config normal_border_color "#3c3836"
bspc config focused_border_color "#fabd2f"
bspc config urgent_border_color "#fb4934"
bspc config presel_border_color "#83a598"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc rule -a '*:*:Picture in picture' \
  state=floating \
  sticky=on \
  follow=off \
  focus=off \
  rectangle=320x180+3020+880

bspc rule -a Emulator state=floating center=on focus=on

#auto start
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
polybar &
dunst &
picom &
fcitx5 &
feh --bg-fill --randomize ~/Downloads/wallpapers/* &
otd-daemon &
